name: deploy-to-github-packages
on: [ push ]
jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permission for mvnw
        run: chmod +x Task-Manager/mvnw

      - name: build backend spring
        working-directory: Task-Manager
        run : ./mvnw clean package

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Use Node.js 18.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: "18.x"
#          cache: 'npm'

      - name: install packages
        working-directory: Task-M-UI
        run: yarn

      - name: build
        working-directory: Task-M-UI
        run: yarn build